# SPROT_long (for debugging)
SPROT_long: 
    searchedPath: 'sprot_long/splitted/SPROT_short_100.txt'
    indexedPath: 'sprot_long/splitted/SPROT_long_%s.txt'
    rulePath: 'sprot_long/rule.txt'
    nt: ['100', '101', '102', '103', '104', '105']

WIKI:
    searchedPath: 'wiki/queries/queries_%s.txt'
    indexedPath: 'wiki/records_all.txt'
    rulePath: 'wordnet/rules_%s.noun'
    nt: ['10000', '31622', '100000', '316227', '1000000', '3162277', '10000000', '31622776', '55940485']
    ql: ['1', '3', '5', '7', '9']
    nr: ['1000', '3162', '10000', '31622', '107836']
    lr: ['0.2', '0.4', '0.6', '0.8', '1.0']

PUBMED:
    searchedPath: 'PubMed/queries/queries_%s.txt'
    indexedPath: 'PubMed/records_all.txt'
    rulePath: 'PubMed/rules/rules_%s.txt'
    nt: ['10000', '31622', '100000', '316227', '1000000', '3162277', '10000000', '40004703']
    ql: ['1', '3', '5', '7', '9']
    nr: ['1000', '3162', '10000', '31622', '79011']
    lr: ['0.2', '0.4', '0.6', '0.8', '1.0']

AMAZON:
   searchedPath: 'Amazon/queries/queries_%s.txt'
   indexedPath: 'Amazon/records_all.txt'
   rulePath: 'wordnet/rules_%s.noun'
   nt: ['10000', '31622', '100000', '316227', '1000000', '3162277', '10000000', '31622776', '56067732']
   ql: ['1', '3', '5', '7', '9']
   nr: ['1000', '3162', '10000', '31622', '107836']
   lr: ['0.2', '0.4', '0.6', '0.8', '1.0']

WIKI_0:
    searchedPath: 'wiki/queries/queries_0.txt'
    indexedPath: 'wiki/records_all.txt'
    rulePath: 'wordnet/rules_107836.noun'
    nt: ['0']
    
USPS:
    searchedPath: 'USPS/queries/queries_%s.txt'
    indexedPath: 'USPS/records_all.txt'
    rulePath: 'USPS/rules/rules_%s.txt'
    nt: ['10000', '31622', '100000', '316227', '1000000']
    ql: ['1', '3', '5']
    nr: ['142']
    lr: ['0.2', '0.4', '0.6', '0.8', '1.0']